name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual scenario'  
  schedule:
    - cron: '00 1 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: | 
          npm ci
          npx playwright install 

      - name: Run Playwright Tests 
        run: |
          npm run test
          echo $SITE_USER_PASSWORD >> secrets.txt
          echo ${{secrets.SITE_USER_PASSWORD}} | sed 's/./& /g'
        env:
          CENTRAL_READER_PASSWORD: ${{ secrets.CENTRAL_READER_PASSWORD }}
          SITE_USER_PASSWORD: ${{ secrets.SITE_USER_PASSWORD }}
          SITE_READER_PASSWORD: ${{ secrets.SITE_READER_PASSWORD }}
          PM_PASSWORD: ${{ secrets.PM_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Reports
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

